In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr)

[1 2 3 4]


In [4]:
print(arr.ndim)

1


In [5]:
print(arr.shape)

(4,)


In [6]:
len(arr)

4

In [7]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500],
])

In [8]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [9]:
print(arr_2d.ndim)

2


In [10]:
print(arr_2d.shape)

(2, 5)


In [11]:
print(len(arr_2d))

2


In [12]:
arr_2d.size

10

In [13]:
arr_3d = np.array([
    [[100, 200, 300, 400, 500]],
])

In [14]:
arr_3d.ndim

3

In [15]:
len(arr_3d)

1

In [16]:
arr_3d.size

5

In [17]:
arr_3d.dtype

dtype('int64')

In [18]:
type(arr_3d)

numpy.ndarray

In [19]:
np.zeros(shape=3)

array([0., 0., 0.])

In [20]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.full(shape = (3,5), fill_value='cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [22]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
foo = np.arange(start=1, stop=5, step=1)

In [25]:
foo[[0,1,2]]

array([1, 2, 3])

In [26]:
foo[np.arange(3)]

array([1, 2, 3])

In [27]:
print(foo[2:])

[3 4]


In [28]:
foo

array([1, 2, 3, 4])

In [29]:
foo[::2]

array([1, 3])

In [30]:
foo[2:]

array([3, 4])

In [31]:
arr_3d

array([[[100, 200, 300, 400, 500]]])

In [32]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [33]:
arr_2d[0,None]

array([[10, 20, 30, 40, 50]])

In [34]:
arr_2d[0]

array([10, 20, 30, 40, 50])

In [35]:
arr_2d[0,1]

np.int64(20)

In [36]:
arr_2d[:1]

array([[10, 20, 30, 40, 50]])

In [37]:
foo = np.arange(start=1, stop=22,step=1).reshape(7,3)

In [38]:
foo

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [39]:
foo[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
foo[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
dailywts = 185 - np.arange(5*7)/5

In [42]:
dailywts.reshape(5,7)

array([[185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8],
       [183.6, 183.4, 183.2, 183. , 182.8, 182.6, 182.4],
       [182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ],
       [180.8, 180.6, 180.4, 180.2, 180. , 179.8, 179.6],
       [179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2]])

In [43]:
(dailywts[5::7] + dailywts[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [44]:
np.arange(start=1,stop=65, step=2).reshape(4,-1)[:,:-1]

array([[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 29],
       [33, 35, 37, 39, 41, 43, 45],
       [49, 51, 53, 55, 57, 59, 61]])

In [84]:
# np.random.seed(55)
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
 
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

gold[locs[:,0],locs[:,1]]

array([2, 6, 2, 8, 2])

In [98]:
arr = np.arange(1,5)
sqr = np.square(arr)
z = np.zeros(5,dtype=int)
z[::2] = sqr[:(z[::2].size)]
z

array([1, 0, 4, 0, 9])

In [122]:
def make_roux(n):
    isEven = (n % 2) == 0
    z = np.zeros(n,dtype=int)
    sqr = np.square(np.arange(1,n))[:(z[isEven::2].size)][::-1]
    z[isEven::2]=sqr[:(z[isEven::2].size)]
    return z

In [125]:
make_roux(12)

array([ 0, 36,  0, 25,  0, 16,  0,  9,  0,  4,  0,  1])

In [115]:
np.square(np.arange(1,8))

array([ 1,  4,  9, 16, 25, 36, 49])

In [131]:
import math
math.ceil((5/2))

3

In [176]:
def make_roux(n):
    size = math.ceil((n/2))
    z = np.zeros(n,dtype=int)
    sqr = np.square(np.arange(1,size+1))
    z[::-2] = sqr
    return z

In [177]:
make_roux(8)

array([ 0, 16,  0,  9,  0,  4,  0,  1])

In [179]:
30 - np.array([17,28]).mean()

np.float64(7.5)

In [181]:
np.array([32,36]).mean() - 30

np.float64(4.0)

In [186]:
np.abs(np.linspace([17,32],[28,36],num=3, axis=1) - 30)[[0,1],[1,1]]

array([7.5, 4. ])

In [187]:
generator = np.random.default_rng()