In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])

In [6]:
print(arr)

[1 2 3 4]


In [7]:
print(arr.ndim)

1


In [8]:
print(arr.shape)

(4,)


In [9]:
len(arr)

4

In [23]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500],
])

In [24]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [22]:
print(arr_2d.ndim)

2


In [15]:
print(arr_2d.shape)

(2, 5)


In [17]:
print(len(arr_2d))

2


In [18]:
arr_2d.size

10

In [26]:
arr_3d = np.array([
    [[100, 200, 300, 400, 500]],
])

In [27]:
arr_3d.ndim

3

In [28]:
len(arr_3d)

1

In [29]:
arr_3d.size

5

In [30]:
arr_3d.dtype

dtype('int64')

In [31]:
type(arr_3d)

numpy.ndarray

In [32]:
np.zeros(shape=3)

array([0., 0., 0.])

In [33]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.full(shape = (3,5), fill_value='cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [35]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [36]:
np.arange(4)

array([0, 1, 2, 3])

In [37]:
foo = np.arange(start=1, stop=5, step=1)

In [38]:
foo[[0,1,2]]

array([1, 2, 3])

In [39]:
foo[np.arange(3)]

array([1, 2, 3])

In [40]:
print(foo[2:])

[3 4]


In [41]:
foo

array([1, 2, 3, 4])

In [42]:
foo[::2]

array([1, 3])

In [44]:
foo[2:]

array([3, 4])

In [45]:
arr_3d

array([[[100, 200, 300, 400, 500]]])

In [46]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [47]:
arr_2d[0,None]

array([[10, 20, 30, 40, 50]])

In [48]:
arr_2d[0]

array([10, 20, 30, 40, 50])

In [49]:
arr_2d[0,1]

np.int64(20)

In [50]:
arr_2d[:1]

array([[10, 20, 30, 40, 50]])

In [63]:
foo = np.arange(start=1, stop=22,step=1).reshape(7,3)

In [64]:
foo

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [67]:
foo[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
foo[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
dailywts = 185 - np.arange(5*7)/5

In [87]:
dailywts.reshape(5,7)

array([[185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8],
       [183.6, 183.4, 183.2, 183. , 182.8, 182.6, 182.4],
       [182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ],
       [180.8, 180.6, 180.4, 180.2, 180. , 179.8, 179.6],
       [179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2]])

In [88]:
(dailywts[5::7] + dailywts[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [100]:
np.arange(start=1,stop=65, step=2).reshape(4,-1)[:,:-1]

array([[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 29],
       [33, 35, 37, 39, 41, 43, 45],
       [49, 51, 53, 55, 57, 59, 61]])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])