In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr)

[1 2 3 4]


In [4]:
print(arr.ndim)

1


In [5]:
print(arr.shape)

(4,)


In [6]:
len(arr)

4

In [7]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500],
])

In [8]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [9]:
print(arr_2d.ndim)

2


In [10]:
print(arr_2d.shape)

(2, 5)


In [11]:
print(len(arr_2d))

2


In [12]:
arr_2d.size

10

In [13]:
arr_3d = np.array([
    [[100, 200, 300, 400, 500]],
])

In [14]:
arr_3d.ndim

3

In [15]:
len(arr_3d)

1

In [16]:
arr_3d.size

5

In [17]:
arr_3d.dtype

dtype('int64')

In [18]:
type(arr_3d)

numpy.ndarray

In [19]:
np.zeros(shape=3)

array([0., 0., 0.])

In [20]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.full(shape = (3,5), fill_value='cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [22]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
foo = np.arange(start=1, stop=5, step=1)

In [25]:
foo[[0,1,2]]

array([1, 2, 3])

In [26]:
foo[np.arange(3)]

array([1, 2, 3])

In [27]:
print(foo[2:])

[3 4]


In [28]:
foo

array([1, 2, 3, 4])

In [29]:
foo[::2]

array([1, 3])

In [30]:
foo[2:]

array([3, 4])

In [31]:
arr_3d

array([[[100, 200, 300, 400, 500]]])

In [32]:
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [33]:
arr_2d[0,None]

array([[10, 20, 30, 40, 50]])

In [34]:
arr_2d[0]

array([10, 20, 30, 40, 50])

In [35]:
arr_2d[0,1]

np.int64(20)

In [36]:
arr_2d[:1]

array([[10, 20, 30, 40, 50]])

In [37]:
foo = np.arange(start=1, stop=22,step=1).reshape(7,3)

In [38]:
foo

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [39]:
foo[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
foo[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
dailywts = 185 - np.arange(5*7)/5

In [42]:
dailywts.reshape(5,7)

array([[185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8],
       [183.6, 183.4, 183.2, 183. , 182.8, 182.6, 182.4],
       [182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ],
       [180.8, 180.6, 180.4, 180.2, 180. , 179.8, 179.6],
       [179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2]])

In [43]:
(dailywts[5::7] + dailywts[6::7])/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [44]:
np.arange(start=1,stop=65, step=2).reshape(4,-1)[:,:-1]

array([[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 29],
       [33, 35, 37, 39, 41, 43, 45],
       [49, 51, 53, 55, 57, 59, 61]])

In [84]:
# np.random.seed(55)
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
 
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

gold[locs[:,0],locs[:,1]]

array([2, 6, 2, 8, 2])

In [98]:
arr = np.arange(1,5)
sqr = np.square(arr)
z = np.zeros(5,dtype=int)
z[::2] = sqr[:(z[::2].size)]
z

array([1, 0, 4, 0, 9])

In [122]:
def make_roux(n):
    isEven = (n % 2) == 0
    z = np.zeros(n,dtype=int)
    sqr = np.square(np.arange(1,n))[:(z[isEven::2].size)][::-1]
    z[isEven::2]=sqr[:(z[isEven::2].size)]
    return z

In [125]:
make_roux(12)

array([ 0, 36,  0, 25,  0, 16,  0,  9,  0,  4,  0,  1])

In [115]:
np.square(np.arange(1,8))

array([ 1,  4,  9, 16, 25, 36, 49])

In [131]:
import math
math.ceil((5/2))

3

In [176]:
def make_roux(n):
    size = math.ceil((n/2))
    z = np.zeros(n,dtype=int)
    sqr = np.square(np.arange(1,size+1))
    z[::-2] = sqr
    return z

In [177]:
make_roux(8)

array([ 0, 16,  0,  9,  0,  4,  0,  1])

In [179]:
30 - np.array([17,28]).mean()

np.float64(7.5)

In [181]:
np.array([32,36]).mean() - 30

np.float64(4.0)

In [186]:
np.abs(np.linspace([17,32],[28,36],num=3, axis=1) - 30)[[0,1],[1,1]]

array([7.5, 4. ])

In [31]:
generator = np.random.default_rng(1010)

In [32]:
love_scores = np.round(generator.uniform(low=0,high=100,size=10),2)
mod = love_scores[:,np.newaxis]
transposed = mod.T
print(mod)
print(np.abs(transposed - mod))
print(np.abs(love_scores[:,None] - love_scores[None,:]))

[[ 9.5 ]
 [53.58]
 [91.77]
 [98.15]
 [84.88]
 [74.61]
 [40.94]
 [56.49]
 [ 8.39]
 [64.69]]
[[ 0.   44.08 82.27 88.65 75.38 65.11 31.44 46.99  1.11 55.19]
 [44.08  0.   38.19 44.57 31.3  21.03 12.64  2.91 45.19 11.11]
 [82.27 38.19  0.    6.38  6.89 17.16 50.83 35.28 83.38 27.08]
 [88.65 44.57  6.38  0.   13.27 23.54 57.21 41.66 89.76 33.46]
 [75.38 31.3   6.89 13.27  0.   10.27 43.94 28.39 76.49 20.19]
 [65.11 21.03 17.16 23.54 10.27  0.   33.67 18.12 66.22  9.92]
 [31.44 12.64 50.83 57.21 43.94 33.67  0.   15.55 32.55 23.75]
 [46.99  2.91 35.28 41.66 28.39 18.12 15.55  0.   48.1   8.2 ]
 [ 1.11 45.19 83.38 89.76 76.49 66.22 32.55 48.1   0.   56.3 ]
 [55.19 11.11 27.08 33.46 20.19  9.92 23.75  8.2  56.3   0.  ]]
[[ 0.   44.08 82.27 88.65 75.38 65.11 31.44 46.99  1.11 55.19]
 [44.08  0.   38.19 44.57 31.3  21.03 12.64  2.91 45.19 11.11]
 [82.27 38.19  0.    6.38  6.89 17.16 50.83 35.28 83.38 27.08]
 [88.65 44.57  6.38  0.   13.27 23.54 57.21 41.66 89.76 33.46]
 [75.38 31.3   6.89 13.27 

In [57]:
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))
 
scores[(scores < 60).nonzero()[0][:3]] = 0

In [89]:

field = np.zeros(shape = (10, 10))
generator = np.random.default_rng(1234)
vals = np.round(generator.normal(size=20),2)
indexes = generator.choice(field.size, len(vals),replace=False)
field.ravel()[indexes] = vals
print(field)

[[ 0.52  0.    0.   -1.48  0.    2.91  0.    0.    0.    0.  ]
 [ 0.   -1.27  0.    0.    0.   -1.6   0.    1.73  0.    0.  ]
 [ 0.    0.    0.    0.    0.43  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.34  0.    0.    0.   -1.67]
 [ 0.    0.86  0.74  0.    0.    0.    1.32  0.    0.52  0.  ]
 [ 0.   -1.    0.    0.    0.    0.15  0.    0.    0.    0.  ]
 [ 0.   -0.51  0.   -0.86  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -2.16  0.    0.95  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.06]]


In [94]:
foo = np.array(['a', 'b'])
bar = np.array(['c', 'd'])
np.concatenate((foo,bar),axis=0)
np.vstack((foo,bar))

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [28]:
gen = np.random.default_rng(123)
ratings = np.round(gen.uniform(low=0,high=10.0, size=(10,2)))
ratings[[1,2,7,9],[0,0,0,0]] = np.nan
n = ~(np.isnan(ratings))
# print(ratings)
move_rating = ratings[:,0]
dir_rating = ratings[:,1]
final = np.where(np.isnan(ratings[:,0]),ratings[:,1],ratings[:,0])
np.insert(arr=ratings,values=final,axis=1,obj=2)
# np.where(n,0,ratings)

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [ 5.,  2.,  5.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [nan,  5.,  5.]])